# Generated by Django 4.1 on 2022-09-15 02:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Shop_ID', models.PositiveIntegerField(unique=True)),
                ('Location', models.CharField(default='', max_length=255)),
                ('ABN', models.PositiveIntegerField(null=True, unique=True)),
                ('Image_Location', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('Business_Email', models.EmailField(default='', max_length=254)),
                ('Business_Number', models.CharField(default='', max_length=12, null=True)),
                ('Business_URL', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('Description', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('User_ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rating_ID', models.PositiveIntegerField(unique=True)),
                ('Comment', models.CharField(default='', max_length=255)),
                ('Rating_value', models.DecimalField(decimal_places=2, max_digits=3)),
                ('Reviewee', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='User_as_Rewievee', to=settings.AUTH_USER_MODEL)),
                ('Reviewer', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='User_as_Rewiever', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_ID', models.PositiveIntegerField(unique=True)),
                ('Product_name', models.CharField(default='', max_length=70)),
                ('Sell_Price', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('Rent_Price', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('Sponsor_Status', models.BooleanField(default=False)),
                ('Shop_ID', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Store.shop')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order_ID', models.PositiveIntegerField(unique=True)),
                ('Order_date', models.DateField()),
                ('Delivery_ID', models.PositiveIntegerField(default=0, unique=True)),
                ('Product_ID', models.PositiveIntegerField(unique=True)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('Customer_ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Shop_ID', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Store.shop')),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Media_ID', models.PositiveIntegerField(unique=True)),
                ('Storage_location', models.CharField(default='', max_length=255)),
                ('Product_ID', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Store.products')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address_line1', models.CharField(default='', max_length=255)),
                ('Address_line2', models.CharField(default='', max_length=255, null=True)),
                ('City', models.CharField(default='', max_length=70)),
                ('Zip', models.PositiveIntegerField()),
                ('State', models.CharField(default='', max_length=50)),
                ('User_ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
