# Generated by Django 4.1 on 2022-09-15 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0005_blog_rename_image_location_shop_banner_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='Description',
        ),
        migrations.AddField(
            model_name='product_description',
            name='Description',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product_description',
            name='Age_Range',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product_description',
            name='Brand',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product_description',
            name='Colour',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product_description',
            name='Type',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
