# Generated by Django 4.1 on 2022-10-05 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0008_shop_business_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='Is_Available',
            field=models.BooleanField(default=True),
        ),
    ]
