# Generated by Django 4.1 on 2022-09-22 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0009_products_is_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('First_Name', models.CharField(default='', max_length=255)),
                ('Last_Name', models.CharField(default='', max_length=255)),
                ('Subject', models.CharField(default='', max_length=255)),
                ('Message', models.TextField(default='', max_length=10000)),
            ],
        ),
    ]
