# Generated by Django 4.1 on 2022-10-07 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0010_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='Email',
            field=models.EmailField(max_length=255),
        ),
    ]
