# Generated by Django 4.1 on 2022-10-08 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Store', '0011_alter_contact_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cart_ID', models.PositiveIntegerField(unique=True)),
                ('Buy_Or_Rent', models.BooleanField(default=True)),
                ('Customer_ID', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Product_ID', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Store.products')),
            ],
        ),
    ]
