# Generated by Django 4.1.2 on 2022-10-09 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0012_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='City',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='Email',
            field=models.EmailField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='First_Name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='Last_Name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='Phone',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='State',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AddField(
            model_name='order',
            name='ZIP',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
