# Generated by Django 4.1 on 2022-10-14 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0014_remove_order_delivery_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='Stock',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
