# Generated by Django 4.1 on 2022-09-13 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_alter_newuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='image_location',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
