# Generated by Django 4.1 on 2022-09-13 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_newuser_image_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='image_location',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
