"""
Django settings for WeBike project.

Generated by 'django-admin startproject' using Django 4.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

import Apps
from pathlib import Path
import sys
import os


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
sys.path.insert(0, os.path.join(BASE_DIR, 'Apps'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-rpg8$g(tf*x#at+z!dudzqj(fcq+ez+w7ft7t$c$qa-hv&i1j*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'Account',
    'Store',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'sslserver',
    'social_django',
]
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'social_django.middleware.SocialAuthExceptionMiddleware',
]
AUTH_USER_MODEL = 'Account.NewUser'

ROOT_URLCONF = 'WeBike.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social_django.context_processors.backends',
            ],
        },
    },
]

WSGI_APPLICATION = 'WeBike.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Australia/Sydney'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATIC_ROOT = os.path.join(BASE_DIR, 'assets')

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'Account.NewUser'

LOGIN_URL = "/account/login"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "../login/"

# Django Media Files configuration
MEDIA_URL = 'media/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

STRIPE_PUBLISHABLE_KEY = "pk_test_51LpOEmGN2W7yg1crqaRn7AF1tvR29xWBDPlE6xt0Qjo6Vwprt6TqzToEteN6z6hrhNI34RHdNuIKuGkTbF9pcNsm00ralvuxfO"
STRIPE_SECRET_KEY = "sk_test_51LpOEmGN2W7yg1crfLeqM2n2q9vSTeZIp7pofdQTbbYnrZ5sQMNz8QUJ3lR5XsGG5YDeYiltbNSr1lNSjXtOdydo00K3HJ2ySN"

CONTACT_EMAIL = 'webike.website@gmail.com'
ADMIN_EMAIL = ['webikecustomerservice@gmail.com',]

STRIPE_PUBLISHABLE_KEY = "pk_test_51LpOEmGN2W7yg1crqaRn7AF1tvR29xWBDPlE6xt0Qjo6Vwprt6TqzToEteN6z6hrhNI34RHdNuIKuGkTbF9pcNsm00ralvuxfO"
STRIPE_SECRET_KEY = "sk_test_51LpOEmGN2W7yg1crfLeqM2n2q9vSTeZIp7pofdQTbbYnrZ5sQMNz8QUJ3lR5XsGG5YDeYiltbNSr1lNSjXtOdydo00K3HJ2ySN"

CONTACT_EMAIL = 'webike.website@gmail.com'
ADMIN_EMAIL = ['webikecustomerservice@gmail.com', ]

# # Twilio SendGrid
EMAIL_HOST = 'smtp.sendgrid.net'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'apikey'
EMAIL_HOST_PASSWORD = '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'

AUTHENTICATION_BACKENDS = [
    'social_core.backends.google.GoogleOAuth2',
    'social_core.backends.facebook.FacebookOAuth2',
    'django.contrib.auth.backends.ModelBackend',
]

SOCIAL_AUTH_FACEBOOK_KEY = "1111855649463244"
SOCIAL_AUTH_FACEBOOK_SECRET = "9957e9578da9cf59f3d15c7df7abcb7e"
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = "352540558782-qtnluue6g5is4jjuuh5spvtafsak87s7.apps.googleusercontent.com"
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = "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"

SOCIAL_AUTH_FACEBOOK_EXTRA_DATA = [
    ('name', 'name'),
    ('email', 'email'),
    ('picture', 'picture'),
    ('link', 'profile_url'),
]


SOCIAL_AUTH_PIPELINE = (
    'social_core.pipeline.social_auth.social_details',
    'social_core.pipeline.social_auth.social_uid',
    'social_core.pipeline.social_auth.social_user',
    'social_core.pipeline.user.get_username',
    'social_core.pipeline.social_auth.associate_by_email',
    'social_core.pipeline.user.create_user',
    'social_core.pipeline.social_auth.associate_user',
    'social_core.pipeline.social_auth.load_extra_data',
    'social_core.pipeline.user.user_details',
)

DEFAULT_FROM_EMAIL = 'webike.website@gmail.com'

